name: Android Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branchName }}
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Create key
        env:
          BASE64_STRING: ${{ secrets.KEY_BASE64 }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
        run: echo "${BASE64_STRING}" | base64 --decode > "${KEY_PATH}"
      - name: Store secrets in local.properties
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          echo "keyAlias=${KEY_ALIAS}" > local.properties
          echo "keyPassword=${KEY_PASSWORD}" >> local.properties
          echo "keyPath=${KEY_PATH}" >> local.properties
          echo "storePassword=${STORE_PASSWORD}" >> local.properties
      - name: Generate APK
        run: ./gradlew :app:assembleRelease --stacktrace
      - name: Clean up
        env:
          KEY_PATH: ${{ secrets.KEY_PATH }}
        run: |
          rm -f ${KEY_PATH}
          rm -f local.properties
      - name: Upload APK to Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
